services:
  auralis:
    build:
      context: .
    network_mode: host
    restart: unless-stopped
    volumes:
      - /home/kwa/.cache/huggingface:/root/.cache/huggingface
      - ./.cache/pip:/root/.cache/pip
    deploy:
      resources:
        reservations:
          devices:
          - driver: cdi
            capabilities: [gpu]
            device_ids:
            - nvidia.com/gpu=all
    command: --host 127.0.0.1 --port 8001 --model AstraMindAI/xttsv2 --gpt_model AstraMindAI/xtts2-gpt --max_concurrency 8 --vllm_logging_level warn
